# Generated by Django 4.2.4 on 2024-01-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0002_alter_category_options'),
        ('BudgetPlanner', '0002_expenseb_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=266)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_expense', to='expenses.expense')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Expenseb',
        ),
    ]
