# Generated by Django 4.2.4 on 2024-01-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BudgetPlanner', '0003_expense2_delete_expenseb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.FloatField()),
                ('education_budget', models.FloatField()),
                ('medical_budget', models.FloatField()),
                ('food_budget', models.FloatField()),
                ('entertainment_budget', models.FloatField()),
                ('transport_budget', models.FloatField()),
                ('personal_care_budget', models.FloatField()),
                ('housing_bills_budget', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
